### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by em-qu** [PavelFr8/Golang-Calc#1]
*Note: Поскольку тестов в задании не было, по этому пункту макс. балл в любом случае.*
1.  Хорошо бы прописать в комментариях назначение каждой функции, что она делает.
1.  Вопрос автору. Зачем использована вот эта обертка func CalcHandler(logger *zap.Logger) http.HandlerFunc ? Можно ли без нее? Ответить можно тут же в ишью.
1.   application_test.go -
     * очень много общего кода в трех функциях, нужно переписать в одну,
     * тест-кейсов маловато,
     * не вижу тест-кейса на корректное выражение.

**Comment by PavelFr8** [comment]
1. Согласен
2. Без неё можно. В процессе работы я брал как пример логгер из учебника, где в мидлвари использовалась похожая обертка. Первоначально, я забыл про пример в учебнике и пытался добавить логирование напрямую в хендлер, соответственно ответ таков - Такая странная обертка осталась, так как раньше логирование было внутри хендлера, а потом я его перенес в отдельную мидлварь, а передачу логера в хендлер забыл убрать
3. тест кейс на корректность выражения присутствует 32 строчка application_test.go

**Comment by em-qu** [comment]
2. Это вопрос на понимание. Ок. Ну раз не используешь логгер, то убери эту обертку, она лишняя.
3. Тут два кейса - https://github.com/PavelFr8/Golang-Calc/blob/master/internal/application/application_test.go#L32
```
		{`{"expression": "7777/0"}`, http.StatusInternalServerError, "Internal server error"},
		{`{"expression": "invalid_expression"}`, http.StatusUnprocessableEntity, "Expression is not valid"},
```
Имею в виду нету кейса, когда выражение валидное.

**Comment by PavelFr8** [comment]
3. Окей, подловил) Я забыл самое простое) Как говориться you have a point  😉

**Comment by PavelFr8** [comment]
Кстати круто код чекаешь, респектую
